### ISSUE TITLE
Jump Jets?

### ISSUE THREAD

**Issue by Nodachi216** [CptMoore/MechEngineMod#1]
If I understand this mod correctly, someone can use a larger rated engine to increase their mech's speed. Did you also account for the additional jump capacity that would allow?

**Comment by Nodachi216** [comment]
Yeah, in TT a mech can have jump jets equal to its walk speed. As an example, A Hunchback has a walk speed of 4, so it can have up to 4 jump jets (you'd have to strip it to make the weight for them of course.)

**Comment by CptMoore** [comment]
wait a minute, don't close this. since its related to engine ratings and speeds, I'll have to implement this.

I can do this dynamically, so you add an engine with a lower rating, have less walk speeds, then tell the user that the mechs loadout is invalid.

are there any other limitations related to JJ? like maybe cannon? (some mechs having JJ, some mechs dont have JJ?)

**Comment by Nodachi216** [comment]
Sorry, wasn't paying attention and must have accidentally hit "Close and comment."

In the lore, yes, some mechs don't have JJ but the actual construction rules do not prohibit JJ from any mech, even the quads could be built to jump!

**Comment by CptMoore** [comment]
Cool, do you know of any rules regarding costs or time to install?

**Comment by CptMoore** [comment]
Ok i added some kind of formula to dynamically calculate the jump jets.

**Comment by CptMoore** [comment]
crusher_bob already made the algorithm TT ready, stay tuned for a release soon
