### ISSUE TITLE
add gyros as full blown components

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#12]
- instead of just upgrades, add actual gyros
- reuse the upgraded one as new gyro ++ while introducing stock gyros
- there are light and standard gyros

make engine one slot and gyro one
the gyro ++ should take 2 slots (so engine + gyro++ = base game gyro upgrade)

dont forget to add weight calculations dynamically based on ~~max tonnage~~ engine rating

can easily be done:
- autoconvert existing gryo upgrade to be actual gyros (use jsons to adjust existing gyro descriptions)
- have 2 different kinds of gyros (easy, just use json and change effects)
- make gyros dynamically change tonnage based on engine rating

unsure on how to do:
- make gyros have new gameplay effects (e.g. critted gyro = no JJ or sprint, but those kinda lame, we need new gameplay, not limit existing ones)

**Comment by CrusherBob** [comment]
Gyro weight is based on engine rating.  Not sure how to pull out currently installed engine rating to set gyro weight.

In theory, damaged/destroyed gyro should increase taken stability damage.  Looks like this might be doable, as the reduced stability damage gyro upgrades just multiply taken stability damage by a number less than 1.

**Comment by CptMoore** [comment]
probably we should only start doing gyros once we have collected a lot of upgrade ideas and negative effects as a list, otherwise gyros don't seem to have enough of an impact in order to be in the first full release, right? always keeping #3 in mind.

**Comment by CptMoore** [comment]
it makes no sense to have gyro weights added to the engine components, let make them dynamically calculated

**Comment by CrusherBob** [comment]
There's some game design theory about avoiding 'death spirals': where an 'early' loss means that you can't win the game, but if you don't know enough about the game, you don't know you passed the no win point some time ago.  Xcom is sorta infamous for that; at least some work went into specifically avoiding that for Battletech, though.  That's why, for example, new mechs and new guns seem relatively easy to get.  If you almost never take internal damage and never really lose any guns, then you are swimming in replacements.  But have seen at least some forum posts where people seem to be losing bits left and right.

That's part of why I wanted to look at how things like engine destruction on mechs, common-ness of available salvaged engines, and so one would actually work in the campaign before committing the making bog standard engines in shops 'rare'.

But for a real test, we need also some people to play who are much worse at the game.  So my default idea was simply to make up to rating 200 or so engines available at any shop that sold an LRM10, and make the 201-400 rating engines available at shops at industrial worlds (or whatever the actual shop flag is) that sell LRM15s and 20s.

Then, if engines were common enough in the game after some playtesting, see about making them appear in the shop 'special' section, rather than the 'inventory' section.  Of course, any rarer engine can be much rarer, as you don't need a special engine to drop your mechs in contracts.

----------------------

On engine pricing:
In TT, bigger engines make mechs more expensive.  But looking at the in game cost of mechs, the faster ones (with bigger engines) aren't really any more expensive that the slower mechs.
Example: a 50 ton 4/6 mech (centurion) is 2,692,000 for just the engine, chassis, etc; a 50 ton 5/8 mech (trebuchet) is 3,392,000

In the game, centurion A 4.2M | Centurion AL 4.3M | Trebuchet 4.6M

So my spitball answer to the cost of engines was to make std engines 500,000 C-Bills: expensive, but not likely to either break the bank if you had to buy them; nor likely to give you a lot of spare money if you had a lot of salvaged ones to sell.

Then Engines with DHS would cost 1.1M (in game each DHS is around 600,000 c-bills); but ~6.5M might actually be a better number.  


I'm not sure what pricing to set for DHS in engine, since that's pretty much the biggest single upgrade possible for any mech.  Of course, in TT it's quite cheap (around 100,000 C-bills).

**Comment by CptMoore** [comment]
Dhs and shs for engines will be its own conponent you have to buy. That solves having to have dhs and shs engines.

Regarding costs and availability your ideas sound resonable.

**Comment by CptMoore** [comment]
Making gyros their own thing would not fit in the timeline, as all additional variants are first introduced in the future.
compact gyro
xl gyro
heavy duty gyro

closing this unless we make a future TT mod
