### ISSUE TITLE
minimize new json count

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#3]
since we can't remove items or risk break skirmish mechlab and save games, we should make sure to only add as few items as possible

- do we really need XL engines? they are complicated to use, should not be available for the timeline anyway. this is basically only for the 2 SLDF mechs you get (and for further modders)
- do we need that many std engines? this will clutter the equipment screen for selling items
- remove the test urban mech

Note this issues is in conflict with #5

**Comment by CrusherBob** [comment]
One of the things that the lore has always supported, but the rules never have is frankenmechs.  From posting by some people who play the game (and weren't very good at it) they were fielding mechs armed with whatever guns they could scrape together and stick on a mech.  So I'd like to at least write in the support for people to play that way with engines as well.

Of course, the second requirement would be to actually balance things better, so that optimal and non-optimal designs are much closer together.  

Of course, this style may not interested everyone.  That's part of the reason I'm including so many switches in the setup section.  For example, you can AllowNonIntWalkValues = false, and that will greatly limit the number of engines per mech you have to look at.

**Comment by CptMoore** [comment]
> frankenmechs

yea thats what #5 would even support more

> balance 

#13 created that issue where one can discuss balance

this ticket is just to make sure we don't add anything that we don't want to stay added for the lifetime of the game

**Comment by CptMoore** [comment]
I reduced the number of engines down a bit. Right now the game slows down considerably the more items you have. There is a rumor going on that HBS is trying to fix these issues, but I'm not sure about when or how.

Adding engines is now easy, since there is a script that can generate engines component jsons.
